# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Project CI-CD Cloud Formation Template
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacityLab.pem
      ImageId: 'ami-0f5c20eac29836e5b' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t2.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0